version: "3"
services:
  multiplication-database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - microservices
    volumes:
      - ~/postgresql/multiplication-database:/var/lib/postgresql/data
  gamification-database:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - microservices
    volumes:
      - ~/postgresql/gamification-database:/var/lib/postgresql/data
  consul-importer:
    image: consul-importer:1.0
    depends_on:
      - consul-dev
    networks:
      - microservices
  consul-dev:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -node=learnmicro -client=0.0.0.0 -log-level=INFO"
    networks:
      - microservices
  rabbitmq-dev:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices
  multiplication:
    image: multiplication:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:postgresql://multiplication-database/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - rabbitmq-dev
      - multiplication-database
      - consul-importer
    networks:
      - microservices
  gamification:
    image: gamification:latest
    # container_name: gamification
    # build: ./gamification
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gamification-database/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - rabbitmq-dev
      - gamification-database
      - consul-importer
    networks:
      - microservices
  gateway-server:
    image: gateway-server:latest
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices
networks:
  microservices:
    driver: bridge
